trigger:
  - main

pool:
  vmImage: windows-latest

steps:
  - script: |
      curl -O https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe 

      hyperexecute.exe -u anubhas -k OmOOOshGyRoUgkriuFPDqahTb1fHdRHGXFPyStZb3BEXIQi1hg -i yaml/win/testng_hyperexecute_autosplit_sample.yaml
